apiVersion: v1
kind: Service
metadata:
  name: microservicio-java-service
spec:
  type: NodePort
  selector:
    app: microservicio-java 
  ports:
    - protocol: TCP
      port: 80            
      targetPort: 8080    
      nodePort: 30001     # External port for NodePort service
